vscode:
  extensions:
    - dracula-theme.theme-dracula@2.18.1:XgpbxhhUSPGI4YfNBYpr1A==
    - PKief.material-icon-theme@3.9.1:g1O+jL+iaYZp5mMmzpPEug==
    - Shan.code-settings-sync@3.4.3:lADxYq3EKc+4gqNNppMuiQ==
    - ms-python.python@2019.10.44104:fKYRb8X8FA37fMd+hgvv2A==